apiVersion: v1
kind: Service
metadata:
  name: title
spec:
  selector:
    app: title
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 33000
  type: LoadBalancer
  