apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      name: auth
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: python-blog-auth:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_HOST
              value: "mongodb"
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DATABASE
              value: "blog_auth"
            - name: MONGODB_COLLECTION
              value: "auth"
            - name: JWT_SECRET_KEY
              value: "your-secret-key-here"
            - name: JWT_ALGORITHM
              value: "HS256"
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "30"
            - name: "MONGODB_USERNAME"
              valueFrom:
                secretKeyRef:
                  key: secrets
                  name: mongodb_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: secrets
                  name: mongodb_password
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              port: 8000
              path: /health
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
      