apiVersion: v1
kind: Service
metadata:
  name: metrics
spec:
  selector:
    app: metrics
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 32317
      targetPort: 8000
  type: LoadBalancer
  