apiVersion: apps/v1
kind: Deployment
metadata:
  name: medias
  labels:
    app: medias
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medias
  template:
    metadata:
      name: medias
      labels:
        app: medias
    spec:
      containers:
        - name: medias
          image: python-blog-medias:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_HOST
              value: "mongodb"
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DATABASE
              value: "blog_auth"
            - name: MONGODB_COLLECTION
              value: "auth"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: MINIO_SECRET
                  name: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: MINIO_SECRET
                  name: MINIO_SECRET_KEY
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              port: 8000
              path: /health
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
      