apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../deploy.yaml
  - ../../svc.yaml
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: metrics
        labels:
          app: metrics
      spec:
        selector:
          matchLabels:
            app: metrics
        template:
          metadata:
            name: metrics
            labels:
              app: metrics
          spec:
            containers:
              - name: metrics
                image: python-blog-metrics:latest
                env:
                  - name: MINIO_HOST
                    value: "minio"
                  - name: MINIO_PORT
                    value: "9000"
                  - name: MINIO_BUCKET
                    value: "medias"
                  - name: MINIO_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        key: MINIO_SECRET
                        name: MINIO_ACCESS_KEY
                  - name: MINIO_SECRET_KEY
                    valueFrom:
                      secretKeyRef:
                        key: MINIO_SECRET
                        name: MINIO_SECRET_KEY
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: metrics
      spec:
        selector:
          app: metrics
        ports:
          - nodePort: 32316
namePrefix: python
nameSuffix: blog
namespace: blog-python
secretGenerator:
  - name: MINIO_SECRET
    type: Opaque
    literals:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin