apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../deploy.yaml
  - ../../svc.yaml
patches:
  - path: deployment.yaml
namePrefix: python
nameSuffix: blog
namespace: blog-python
secretGenerator:
  - name: MINIO_SECRET
    type: Opaque
    literals:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin