apiVersion: apps/v1
kind: Deployment
metadata:
  name: title
  labels:
    app: title
spec:
  replicas: 1
  selector:
    matchLabels:
      app: title
  template:
    metadata:
      name: title
      labels:
        app: title
    spec:
      containers:
        - name: title
          image: image
          imagePullPolicy: Always
          env:
            - name: MONGODB_HOST
              value: "mongodb"
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DATABASE
              value: "blog_auth"
            - name: MONGODB_COLLECTION
              value: "ads"
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: secrets
                  name: mongodb_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: secrets
                  name: mongodb_password
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
      