apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
  labels:
    app: posts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      name: posts
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: python-blog-posts:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_HOST
              value: "mongodb"
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DATABASE
              value: "blog_auth"
            - name: MONGODB_COLLECTION
              value: "auth"
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: secrets
                  name: mongodb_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: secrets
                  name: mongodb_password
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              port: 8000
              path: /health
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
      