apiVersion: v1
kind: Service
metadata:
  name: posts
spec:
  selector:
    app: posts
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 32318
      targetPort: 8000
  type: LoadBalancer
  