apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: title
    patch: |-
      - op: replace
        path: /metadata/name
        value: "frontend"
      - op: replace
        path: /metadata/labels/app
        value: "frontend"
      - op: replace
        path: /spec/selector/matchLabels/app
        value: "frontend"
      - op: replace
        path: /spec/template/metadata/name
        value: "frontend"
      - op: replace
        path: /spec/template/metadata/labels/app
        value: "frontend"
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: "frontend"
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: "frontend"
  - target:
      kind: Service
      name: title
      version: v1
    patch: |-
      - op: add
        path: /spec/ports/0/nodePort
        value: 32315
      - op: replace
        path: /metadata/name
        value: "frontend"
      - op: replace
        path: /spec/selector/app
        value: "frontend"
namePrefix: python-
nameSuffix: -blog
namespace: blog-python
images:
  - name: image
    newName: python-blog-frontend
    newTag: latest
secretGenerator:
  - name: MONGODB_SECRET
    type: Opaque
    literals:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=password