apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../deploy.yaml
  - ../../svc.yaml
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: frontend
        labels:
          app: frontend
      spec:
        selector:
          matchLabels:
            app: frontend
        template:
          metadata:
            name: frontend
            labels:
              app: frontend
          spec:
            containers:
              - name: frontend
                image: python-blog-frontend:latest
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: frontend
      spec:
        selector:
          app: frontend
        ports:
          - nodePort: 32315
namePrefix: python
nameSuffix: blog
namespace: blog-python
secretGenerator:
  - name: MONGODB_SECRET
    type: Opaque
    literals:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=password